package com.github.elwood612.gufyblocks.blocks.blockUtil;

import com.google.common.base.Suppliers;
import com.google.common.collect.BiMap;
import com.google.common.collect.ImmutableBiMap;
import com.github.elwood612.gufyblocks.util.GufyUtil;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;

import java.util.function.Supplier;

public interface GufyCrackable {
    public static final Supplier<BiMap<Block, Block>> CRACKABLES = Suppliers.memoize(() -> {
        return ImmutableBiMap.<Block, Block>builder()
                // STONE BRICKS
                .put(Blocks.STONE_BRICKS, Blocks.CRACKED_STONE_BRICKS)
                .put(Blocks.STONE_BRICK_STAIRS, GufyUtil.getGufyBlock("cracked_stone_bricks_stairs"))
                .put(Blocks.STONE_BRICK_SLAB, GufyUtil.getGufyBlock("cracked_stone_bricks_slab"))
                .put(Blocks.STONE_BRICK_WALL, GufyUtil.getGufyBlock("cracked_stone_bricks_wall"))
                .put(GufyUtil.getGufyBlock("stone_bricks_verticalslab"), GufyUtil.getGufyBlock("cracked_stone_bricks_verticalslab"))
                .put(GufyUtil.getGufyBlock("stone_bricks_hopper"), GufyUtil.getGufyBlock("cracked_stone_bricks_hopper"))
                .put(GufyUtil.getGufyBlock("stone_bricks_post"), GufyUtil.getGufyBlock("cracked_stone_bricks_post"))
                // STONE TILES
                .put(GufyUtil.getGufyBlock("cobblestone_bricks"), GufyUtil.getGufyBlock("cracked_cobblestone_bricks"))
                .put(GufyUtil.getGufyBlock("cobblestone_bricks_stairs"), GufyUtil.getGufyBlock("cracked_cobblestone_bricks_stairs"))
                .put(GufyUtil.getGufyBlock("cobblestone_bricks_slab"), GufyUtil.getGufyBlock("cracked_cobblestone_bricks_slab"))
                .put(GufyUtil.getGufyBlock("cobblestone_bricks_verticalslab"), GufyUtil.getGufyBlock("cracked_cobblestone_bricks_verticalslab"))
                .put(GufyUtil.getGufyBlock("cobblestone_bricks_wall"), GufyUtil.getGufyBlock("cracked_cobblestone_bricks_wall"))
                .put(GufyUtil.getGufyBlock("cobblestone_bricks_hopper"), GufyUtil.getGufyBlock("cracked_cobblestone_bricks_hopper"))
                .put(GufyUtil.getGufyBlock("cobblestone_bricks_post"), GufyUtil.getGufyBlock("cracked_cobblestone_bricks_post"))
                // DIORITE BRICKS
                .put(GufyUtil.getGufyBlock("diorite_bricks"), GufyUtil.getGufyBlock("cracked_diorite_bricks"))
                .put(GufyUtil.getGufyBlock("diorite_bricks_stairs"), GufyUtil.getGufyBlock("cracked_diorite_bricks_stairs"))
                .put(GufyUtil.getGufyBlock("diorite_bricks_slab"), GufyUtil.getGufyBlock("cracked_diorite_bricks_slab"))
                .put(GufyUtil.getGufyBlock("diorite_bricks_verticalslab"), GufyUtil.getGufyBlock("cracked_diorite_bricks_verticalslab"))
                .put(GufyUtil.getGufyBlock("diorite_bricks_wall"), GufyUtil.getGufyBlock("cracked_diorite_bricks_wall"))
                .put(GufyUtil.getGufyBlock("diorite_bricks_hopper"), GufyUtil.getGufyBlock("cracked_diorite_bricks_hopper"))
                .put(GufyUtil.getGufyBlock("diorite_bricks_post"), GufyUtil.getGufyBlock("cracked_diorite_bricks_post"))
                // DIORITE TILES
                .put(GufyUtil.getGufyBlock("diorite_cobble_bricks"), GufyUtil.getGufyBlock("cracked_diorite_cobble_bricks"))
                .put(GufyUtil.getGufyBlock("diorite_cobble_bricks_stairs"), GufyUtil.getGufyBlock("cracked_diorite_cobble_bricks_stairs"))
                .put(GufyUtil.getGufyBlock("diorite_cobble_bricks_slab"), GufyUtil.getGufyBlock("cracked_diorite_cobble_bricks_slab"))
                .put(GufyUtil.getGufyBlock("diorite_cobble_bricks_verticalslab"), GufyUtil.getGufyBlock("cracked_diorite_cobble_bricks_verticalslab"))
                .put(GufyUtil.getGufyBlock("diorite_cobble_bricks_wall"), GufyUtil.getGufyBlock("cracked_diorite_cobble_bricks_wall"))
                .put(GufyUtil.getGufyBlock("diorite_cobble_bricks_hopper"), GufyUtil.getGufyBlock("cracked_diorite_cobble_bricks_hopper"))
                .put(GufyUtil.getGufyBlock("diorite_cobble_bricks_post"), GufyUtil.getGufyBlock("cracked_diorite_cobble_bricks_post"))
                // GRANITE BRICKS
                .put(GufyUtil.getGufyBlock("granite_bricks"), GufyUtil.getGufyBlock("cracked_granite_bricks"))
                .put(GufyUtil.getGufyBlock("granite_bricks_stairs"), GufyUtil.getGufyBlock("cracked_granite_bricks_stairs"))
                .put(GufyUtil.getGufyBlock("granite_bricks_slab"), GufyUtil.getGufyBlock("cracked_granite_bricks_slab"))
                .put(GufyUtil.getGufyBlock("granite_bricks_verticalslab"), GufyUtil.getGufyBlock("cracked_granite_bricks_verticalslab"))
                .put(GufyUtil.getGufyBlock("granite_bricks_wall"), GufyUtil.getGufyBlock("cracked_granite_bricks_wall"))
                .put(GufyUtil.getGufyBlock("granite_bricks_hopper"), GufyUtil.getGufyBlock("cracked_granite_bricks_hopper"))
                .put(GufyUtil.getGufyBlock("granite_bricks_post"), GufyUtil.getGufyBlock("cracked_granite_bricks_post"))
                // GRANITE TILES
                .put(GufyUtil.getGufyBlock("granite_cobble_bricks"), GufyUtil.getGufyBlock("cracked_granite_cobble_bricks"))
                .put(GufyUtil.getGufyBlock("granite_cobble_bricks_stairs"), GufyUtil.getGufyBlock("cracked_granite_cobble_bricks_stairs"))
                .put(GufyUtil.getGufyBlock("granite_cobble_bricks_slab"), GufyUtil.getGufyBlock("cracked_granite_cobble_bricks_slab"))
                .put(GufyUtil.getGufyBlock("granite_cobble_bricks_verticalslab"), GufyUtil.getGufyBlock("cracked_granite_cobble_bricks_verticalslab"))
                .put(GufyUtil.getGufyBlock("granite_cobble_bricks_wall"), GufyUtil.getGufyBlock("cracked_granite_cobble_bricks_wall"))
                .put(GufyUtil.getGufyBlock("granite_cobble_bricks_hopper"), GufyUtil.getGufyBlock("cracked_granite_cobble_bricks_hopper"))
                .put(GufyUtil.getGufyBlock("granite_cobble_bricks_post"), GufyUtil.getGufyBlock("cracked_granite_cobble_bricks_post"))
                // ANDESITE BRICKS
                .put(GufyUtil.getGufyBlock("andesite_bricks"), GufyUtil.getGufyBlock("cracked_andesite_bricks"))
                .put(GufyUtil.getGufyBlock("andesite_bricks_stairs"), GufyUtil.getGufyBlock("cracked_andesite_bricks_stairs"))
                .put(GufyUtil.getGufyBlock("andesite_bricks_slab"), GufyUtil.getGufyBlock("cracked_andesite_bricks_slab"))
                .put(GufyUtil.getGufyBlock("andesite_bricks_verticalslab"), GufyUtil.getGufyBlock("cracked_andesite_bricks_verticalslab"))
                .put(GufyUtil.getGufyBlock("andesite_bricks_wall"), GufyUtil.getGufyBlock("cracked_andesite_bricks_wall"))
                .put(GufyUtil.getGufyBlock("andesite_bricks_hopper"), GufyUtil.getGufyBlock("cracked_andesite_bricks_hopper"))
                .put(GufyUtil.getGufyBlock("andesite_bricks_post"), GufyUtil.getGufyBlock("cracked_andesite_bricks_post"))
                // NETHER BRICKS
                .put(Blocks.NETHER_BRICKS, Blocks.CRACKED_NETHER_BRICKS)
                .put(Blocks.NETHER_BRICK_STAIRS, GufyUtil.getGufyBlock("cracked_nether_bricks_stairs"))
                .put(Blocks.NETHER_BRICK_SLAB, GufyUtil.getGufyBlock("cracked_nether_bricks_slab"))
                .put(Blocks.NETHER_BRICK_WALL, GufyUtil.getGufyBlock("cracked_nether_bricks_wall"))
                .put(Blocks.NETHER_BRICK_FENCE, GufyUtil.getGufyBlock("cracked_nether_bricks_fence"))
                .put(GufyUtil.getGufyBlock("cracked_nether_bricks_verticalslab"), GufyUtil.getGufyBlock("cracked_nether_bricks_verticalslab"))
                .put(GufyUtil.getGufyBlock("cracked_nether_bricks_hopper"), GufyUtil.getGufyBlock("cracked_nether_bricks_hopper"))
                // DEEPSLATE BRICKS
                .put(Blocks.DEEPSLATE_BRICKS, Blocks.CRACKED_DEEPSLATE_BRICKS)
                .put(Blocks.DEEPSLATE_BRICK_STAIRS, GufyUtil.getGufyBlock("cracked_deepslate_bricks_stairs"))
                .put(Blocks.DEEPSLATE_BRICK_SLAB, GufyUtil.getGufyBlock("cracked_deepslate_bricks_slab"))
                .put(Blocks.DEEPSLATE_BRICK_WALL, GufyUtil.getGufyBlock("cracked_deepslate_bricks_wall"))
                .put(GufyUtil.getGufyBlock("deepslate_bricks_verticalslab"), GufyUtil.getGufyBlock("cracked_deepslate_bricks_verticalslab"))
                .put(GufyUtil.getGufyBlock("deepslate_bricks_hopper"), GufyUtil.getGufyBlock("cracked_deepslate_bricks_hopper"))
                .put(GufyUtil.getGufyBlock("deepslate_bricks_post"), GufyUtil.getGufyBlock("cracked_deepslate_bricks_post"))
                // DEEPSLATE TILES
                .put(Blocks.DEEPSLATE_TILES, Blocks.CRACKED_DEEPSLATE_TILES)
                .put(Blocks.DEEPSLATE_TILE_STAIRS, GufyUtil.getGufyBlock("cracked_deepslate_tiles_stairs"))
                .put(Blocks.DEEPSLATE_TILE_SLAB, GufyUtil.getGufyBlock("cracked_deepslate_tiles_slab"))
                .put(Blocks.DEEPSLATE_TILE_WALL, GufyUtil.getGufyBlock("cracked_deepslate_tiles_wall"))
                .put(GufyUtil.getGufyBlock("deepslate_tiles_verticalslab"), GufyUtil.getGufyBlock("cracked_deepslate_tiles_verticalslab"))
                .put(GufyUtil.getGufyBlock("deepslate_tiles_hopper"), GufyUtil.getGufyBlock("cracked_deepslate_tiles_hopper"))
                .put(GufyUtil.getGufyBlock("deepslate_tiles_post"), GufyUtil.getGufyBlock("cracked_deepslate_tiles_post"))
                // POLISHED BLACKSTONE BRICKS
                .put(Blocks.POLISHED_BLACKSTONE_BRICKS, Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS)
                .put(Blocks.POLISHED_BLACKSTONE_BRICK_STAIRS, GufyUtil.getGufyBlock("cracked_polished_blackstone_brick_stairs"))
                .put(Blocks.POLISHED_BLACKSTONE_BRICK_SLAB, GufyUtil.getGufyBlock("cracked_polished_blackstone_brick_slab"))
                .put(Blocks.POLISHED_BLACKSTONE_BRICK_WALL, GufyUtil.getGufyBlock("cracked_polished_blackstone_brick_wall"))
                .put(GufyUtil.getGufyBlock("polished_blackstone_brick_verticalslab"), GufyUtil.getGufyBlock("cracked_polished_blackstone_brick_verticalslab"))
                .put(GufyUtil.getGufyBlock("polished_blackstone_brick_hopper"), GufyUtil.getGufyBlock("cracked_polished_blackstone_brick_hopper"))
                .put(GufyUtil.getGufyBlock("polished_blackstone_brick_post"), GufyUtil.getGufyBlock("cracked_polished_blackstone_brick_post"))
                // SANDSTONE BRICKS
                .put(GufyUtil.getGufyBlock("sandstone_bricks"), GufyUtil.getGufyBlock("cracked_sandstone_bricks"))
                .put(GufyUtil.getGufyBlock("sandstone_bricks_stairs"), GufyUtil.getGufyBlock("cracked_sandstone_bricks_stairs"))
                .put(GufyUtil.getGufyBlock("sandstone_bricks_slab"), GufyUtil.getGufyBlock("cracked_sandstone_bricks_slab"))
                .put(GufyUtil.getGufyBlock("sandstone_bricks_verticalslab"), GufyUtil.getGufyBlock("cracked_sandstone_bricks_verticalslab"))
                .put(GufyUtil.getGufyBlock("sandstone_bricks_wall"), GufyUtil.getGufyBlock("cracked_sandstone_bricks_wall"))
                .put(GufyUtil.getGufyBlock("sandstone_bricks_hopper"), GufyUtil.getGufyBlock("cracked_sandstone_bricks_hopper"))
                .put(GufyUtil.getGufyBlock("sandstone_bricks_post"), GufyUtil.getGufyBlock("cracked_sandstone_bricks_post"))
                // SANDSTONE TILES
                .put(GufyUtil.getGufyBlock("sandstone_cobble_bricks"), GufyUtil.getGufyBlock("cracked_sandstone_cobble_bricks"))
                .put(GufyUtil.getGufyBlock("sandstone_cobble_bricks_stairs"), GufyUtil.getGufyBlock("cracked_sandstone_cobble_bricks_stairs"))
                .put(GufyUtil.getGufyBlock("sandstone_cobble_bricks_slab"), GufyUtil.getGufyBlock("cracked_sandstone_cobble_bricks_slab"))
                .put(GufyUtil.getGufyBlock("sandstone_cobble_bricks_verticalslab"), GufyUtil.getGufyBlock("cracked_sandstone_cobble_bricks_verticalslab"))
                .put(GufyUtil.getGufyBlock("sandstone_cobble_bricks_wall"), GufyUtil.getGufyBlock("cracked_sandstone_cobble_bricks_wall"))
                .put(GufyUtil.getGufyBlock("sandstone_cobble_bricks_hopper"), GufyUtil.getGufyBlock("cracked_sandstone_cobble_bricks_hopper"))
                .put(GufyUtil.getGufyBlock("sandstone_cobble_bricks_post"), GufyUtil.getGufyBlock("cracked_sandstone_cobble_bricks_post"))
                // RED SANDSTONE BRICKS
                .put(GufyUtil.getGufyBlock("red_sandstone_bricks"), GufyUtil.getGufyBlock("cracked_red_sandstone_bricks"))
                .put(GufyUtil.getGufyBlock("red_sandstone_bricks_stairs"), GufyUtil.getGufyBlock("cracked_red_sandstone_bricks_stairs"))
                .put(GufyUtil.getGufyBlock("red_sandstone_bricks_slab"), GufyUtil.getGufyBlock("cracked_red_sandstone_bricks_slab"))
                .put(GufyUtil.getGufyBlock("red_sandstone_bricks_verticalslab"), GufyUtil.getGufyBlock("cracked_red_sandstone_bricks_verticalslab"))
                .put(GufyUtil.getGufyBlock("red_sandstone_bricks_wall"), GufyUtil.getGufyBlock("cracked_red_sandstone_bricks_wall"))
                .put(GufyUtil.getGufyBlock("red_sandstone_bricks_hopper"), GufyUtil.getGufyBlock("cracked_red_sandstone_bricks_hopper"))
                .put(GufyUtil.getGufyBlock("red_sandstone_bricks_post"), GufyUtil.getGufyBlock("cracked_red_sandstone_bricks_post"))
                // RED SANDSTONE TILES
                .put(GufyUtil.getGufyBlock("red_sandstone_cobble_bricks"), GufyUtil.getGufyBlock("cracked_red_sandstone_cobble_bricks"))
                .put(GufyUtil.getGufyBlock("red_sandstone_cobble_bricks_stairs"), GufyUtil.getGufyBlock("cracked_red_sandstone_cobble_bricks_stairs"))
                .put(GufyUtil.getGufyBlock("red_sandstone_cobble_bricks_slab"), GufyUtil.getGufyBlock("cracked_red_sandstone_cobble_bricks_slab"))
                .put(GufyUtil.getGufyBlock("red_sandstone_cobble_bricks_verticalslab"), GufyUtil.getGufyBlock("cracked_red_sandstone_cobble_bricks_verticalslab"))
                .put(GufyUtil.getGufyBlock("red_sandstone_cobble_bricks_wall"), GufyUtil.getGufyBlock("cracked_red_sandstone_cobble_bricks_wall"))
                .put(GufyUtil.getGufyBlock("red_sandstone_cobble_bricks_hopper"), GufyUtil.getGufyBlock("cracked_red_sandstone_cobble_bricks_hopper"))
                .put(GufyUtil.getGufyBlock("red_sandstone_cobble_bricks_post"), GufyUtil.getGufyBlock("cracked_red_sandstone_cobble_bricks_post"))
                // BRICKS
                .put(Blocks.BRICKS, GufyUtil.getGufyBlock("cracked_bricks"))
                .put(Blocks.BRICK_STAIRS, GufyUtil.getGufyBlock("cracked_bricks_stairs"))
                .put(Blocks.BRICK_SLAB, GufyUtil.getGufyBlock("cracked_bricks_slab"))
                .put(Blocks.BRICK_WALL, GufyUtil.getGufyBlock("cracked_bricks_wall"))
                .put(GufyUtil.getGufyBlock("brick_verticalslab"), GufyUtil.getGufyBlock("cracked_bricks_verticalslab"))
                .put(GufyUtil.getGufyBlock("brick_hopper"), GufyUtil.getGufyBlock("cracked_bricks_hopper"))
                .put(GufyUtil.getGufyBlock("brick_post"), GufyUtil.getGufyBlock("cracked_bricks_post"))
                // FRAMED
                .put(GufyUtil.getGufyBlock("oak_framed_terracotta"), GufyUtil.getGufyBlock("oak_framed_terracotta_left"))
                .put(GufyUtil.getGufyBlock("oak_framed_terracotta_left"), GufyUtil.getGufyBlock("oak_framed_terracotta_right"))
                .put(GufyUtil.getGufyBlock("oak_framed_terracotta_right"), GufyUtil.getGufyBlock("oak_framed_terracotta_cross"))
                .put(GufyUtil.getGufyBlock("oak_framed_terracotta_cross"), GufyUtil.getGufyBlock("oak_framed_terracotta"))
                .put(GufyUtil.getGufyBlock("spruce_framed_terracotta"), GufyUtil.getGufyBlock("spruce_framed_terracotta_left"))
                .put(GufyUtil.getGufyBlock("spruce_framed_terracotta_left"), GufyUtil.getGufyBlock("spruce_framed_terracotta_right"))
                .put(GufyUtil.getGufyBlock("spruce_framed_terracotta_right"), GufyUtil.getGufyBlock("spruce_framed_terracotta_cross"))
                .put(GufyUtil.getGufyBlock("spruce_framed_terracotta_cross"), GufyUtil.getGufyBlock("spruce_framed_terracotta"))
                .put(GufyUtil.getGufyBlock("birch_framed_terracotta"), GufyUtil.getGufyBlock("birch_framed_terracotta_left"))
                .put(GufyUtil.getGufyBlock("birch_framed_terracotta_left"), GufyUtil.getGufyBlock("birch_framed_terracotta_right"))
                .put(GufyUtil.getGufyBlock("birch_framed_terracotta_right"), GufyUtil.getGufyBlock("birch_framed_terracotta_cross"))
                .put(GufyUtil.getGufyBlock("birch_framed_terracotta_cross"), GufyUtil.getGufyBlock("birch_framed_terracotta"))
                .put(GufyUtil.getGufyBlock("dark_oak_framed_terracotta"), GufyUtil.getGufyBlock("dark_oak_framed_terracotta_left"))
                .put(GufyUtil.getGufyBlock("dark_oak_framed_terracotta_left"), GufyUtil.getGufyBlock("dark_oak_framed_terracotta_right"))
                .put(GufyUtil.getGufyBlock("dark_oak_framed_terracotta_right"), GufyUtil.getGufyBlock("dark_oak_framed_terracotta_cross"))
                .put(GufyUtil.getGufyBlock("dark_oak_framed_terracotta_cross"), GufyUtil.getGufyBlock("dark_oak_framed_terracotta"))
                .put(GufyUtil.getGufyBlock("jungle_framed_terracotta"), GufyUtil.getGufyBlock("jungle_framed_terracotta_left"))
                .put(GufyUtil.getGufyBlock("jungle_framed_terracotta_left"), GufyUtil.getGufyBlock("jungle_framed_terracotta_right"))
                .put(GufyUtil.getGufyBlock("jungle_framed_terracotta_right"), GufyUtil.getGufyBlock("jungle_framed_terracotta_cross"))
                .put(GufyUtil.getGufyBlock("jungle_framed_terracotta_cross"), GufyUtil.getGufyBlock("jungle_framed_terracotta"))
                .put(GufyUtil.getGufyBlock("acacia_framed_terracotta"), GufyUtil.getGufyBlock("acacia_framed_terracotta_left"))
                .put(GufyUtil.getGufyBlock("acacia_framed_terracotta_left"), GufyUtil.getGufyBlock("acacia_framed_terracotta_right"))
                .put(GufyUtil.getGufyBlock("acacia_framed_terracotta_right"), GufyUtil.getGufyBlock("acacia_framed_terracotta_cross"))
                .put(GufyUtil.getGufyBlock("acacia_framed_terracotta_cross"), GufyUtil.getGufyBlock("acacia_framed_terracotta"))
                .put(GufyUtil.getGufyBlock("crimson_framed_terracotta"), GufyUtil.getGufyBlock("crimson_framed_terracotta_left"))
                .put(GufyUtil.getGufyBlock("crimson_framed_terracotta_left"), GufyUtil.getGufyBlock("crimson_framed_terracotta_right"))
                .put(GufyUtil.getGufyBlock("crimson_framed_terracotta_right"), GufyUtil.getGufyBlock("crimson_framed_terracotta_cross"))
                .put(GufyUtil.getGufyBlock("crimson_framed_terracotta_cross"), GufyUtil.getGufyBlock("crimson_framed_terracotta"))
                .put(GufyUtil.getGufyBlock("warped_framed_terracotta"), GufyUtil.getGufyBlock("warped_framed_terracotta_left"))
                .put(GufyUtil.getGufyBlock("warped_framed_terracotta_left"), GufyUtil.getGufyBlock("warped_framed_terracotta_right"))
                .put(GufyUtil.getGufyBlock("warped_framed_terracotta_right"), GufyUtil.getGufyBlock("warped_framed_terracotta_cross"))
                .put(GufyUtil.getGufyBlock("warped_framed_terracotta_cross"), GufyUtil.getGufyBlock("warped_framed_terracotta"))
                .put(GufyUtil.getGufyBlock("mangrove_framed_terracotta"), GufyUtil.getGufyBlock("mangrove_framed_terracotta_left"))
                .put(GufyUtil.getGufyBlock("mangrove_framed_terracotta_left"), GufyUtil.getGufyBlock("mangrove_framed_terracotta_right"))
                .put(GufyUtil.getGufyBlock("mangrove_framed_terracotta_right"), GufyUtil.getGufyBlock("mangrove_framed_terracotta_cross"))
                .put(GufyUtil.getGufyBlock("mangrove_framed_terracotta_cross"), GufyUtil.getGufyBlock("mangrove_framed_terracotta"))
                .put(GufyUtil.getGufyBlock("cherry_framed_terracotta"), GufyUtil.getGufyBlock("cherry_framed_terracotta_left"))
                .put(GufyUtil.getGufyBlock("cherry_framed_terracotta_left"), GufyUtil.getGufyBlock("cherry_framed_terracotta_right"))
                .put(GufyUtil.getGufyBlock("cherry_framed_terracotta_right"), GufyUtil.getGufyBlock("cherry_framed_terracotta_cross"))
                .put(GufyUtil.getGufyBlock("cherry_framed_terracotta_cross"), GufyUtil.getGufyBlock("cherry_framed_terracotta"))
                .put(GufyUtil.getGufyBlock("bamboo_framed_terracotta"), GufyUtil.getGufyBlock("bamboo_framed_terracotta_left"))
                .put(GufyUtil.getGufyBlock("bamboo_framed_terracotta_left"), GufyUtil.getGufyBlock("bamboo_framed_terracotta_right"))
                .put(GufyUtil.getGufyBlock("bamboo_framed_terracotta_right"), GufyUtil.getGufyBlock("bamboo_framed_terracotta_cross"))
                .put(GufyUtil.getGufyBlock("bamboo_framed_terracotta_cross"), GufyUtil.getGufyBlock("bamboo_framed_terracotta"))
                .put(GufyUtil.getGufyBlock("mushroom_framed_terracotta"), GufyUtil.getGufyBlock("mushroom_framed_terracotta_left"))
                .put(GufyUtil.getGufyBlock("mushroom_framed_terracotta_left"), GufyUtil.getGufyBlock("mushroom_framed_terracotta_right"))
                .put(GufyUtil.getGufyBlock("mushroom_framed_terracotta_right"), GufyUtil.getGufyBlock("mushroom_framed_terracotta_cross"))
                .put(GufyUtil.getGufyBlock("mushroom_framed_terracotta_cross"), GufyUtil.getGufyBlock("mushroom_framed_terracotta"))
                // CARVED LOGS
                .put(Blocks.STRIPPED_ACACIA_WOOD, GufyUtil.getGufyBlock("chiseled_stripped_acacia_wood"))
                .put(Blocks.STRIPPED_BIRCH_WOOD, GufyUtil.getGufyBlock("chiseled_stripped_birch_wood"))
                .put(Blocks.STRIPPED_BAMBOO_BLOCK, GufyUtil.getGufyBlock("chiseled_stripped_bamboo_block"))
                .put(Blocks.STRIPPED_CRIMSON_HYPHAE, GufyUtil.getGufyBlock("chiseled_stripped_crimson_hyphae"))
                .put(Blocks.STRIPPED_DARK_OAK_WOOD, GufyUtil.getGufyBlock("chiseled_stripped_dark_oak_wood"))
                .put(Blocks.STRIPPED_JUNGLE_WOOD, GufyUtil.getGufyBlock("chiseled_stripped_jungle_wood"))
                .put(Blocks.STRIPPED_OAK_WOOD, GufyUtil.getGufyBlock("chiseled_stripped_oak_wood"))
                .put(Blocks.STRIPPED_MANGROVE_WOOD, GufyUtil.getGufyBlock("chiseled_stripped_mangrove_wood"))
                .put(Blocks.STRIPPED_CHERRY_WOOD, GufyUtil.getGufyBlock("chiseled_stripped_cherry_wood"))
                .put(Blocks.STRIPPED_SPRUCE_WOOD, GufyUtil.getGufyBlock("chiseled_stripped_spruce_wood"))
                .put(Blocks.STRIPPED_WARPED_HYPHAE, GufyUtil.getGufyBlock("chiseled_stripped_warped_hyphae"))

                .build();
    });
}
