package com.github.elwood612.gufyblocks.blocks.blockUtil;

import com.google.common.base.Suppliers;
import com.google.common.collect.BiMap;
import com.google.common.collect.ImmutableBiMap;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;

import java.util.function.Supplier;

import static com.github.elwood612.gufyblocks.util.GufyUtil.getGufyBlock;

public interface GufyCrackable {
    public static final Supplier<BiMap<Block, Block>> CRACKABLES = Suppliers.memoize(() -> {
        return ImmutableBiMap.<Block, Block>builder()
                // STONE BRICKS
                .put(Blocks.STONE_BRICKS, Blocks.CRACKED_STONE_BRICKS)
                .put(Blocks.STONE_BRICK_STAIRS, getGufyBlock("cracked_stone_bricks_stairs"))
                .put(Blocks.STONE_BRICK_SLAB, getGufyBlock("cracked_stone_bricks_slab"))
                .put(Blocks.STONE_BRICK_WALL, getGufyBlock("cracked_stone_bricks_wall"))
                .put(getGufyBlock("stone_bricks_verticalslab"), getGufyBlock("cracked_stone_bricks_verticalslab"))
                .put(getGufyBlock("stone_bricks_hopper"), getGufyBlock("cracked_stone_bricks_hopper"))
                .put(getGufyBlock("stone_bricks_post"), getGufyBlock("cracked_stone_bricks_post"))
                // STONE TILES
                .put(getGufyBlock("cobblestone_bricks"), getGufyBlock("cracked_cobblestone_bricks"))
                .put(getGufyBlock("cobblestone_bricks_stairs"), getGufyBlock("cracked_cobblestone_bricks_stairs"))
                .put(getGufyBlock("cobblestone_bricks_slab"), getGufyBlock("cracked_cobblestone_bricks_slab"))
                .put(getGufyBlock("cobblestone_bricks_verticalslab"), getGufyBlock("cracked_cobblestone_bricks_verticalslab"))
                .put(getGufyBlock("cobblestone_bricks_wall"), getGufyBlock("cracked_cobblestone_bricks_wall"))
                .put(getGufyBlock("cobblestone_bricks_hopper"), getGufyBlock("cracked_cobblestone_bricks_hopper"))
                .put(getGufyBlock("cobblestone_bricks_post"), getGufyBlock("cracked_cobblestone_bricks_post"))
                // DIORITE BRICKS
                .put(getGufyBlock("diorite_bricks"), getGufyBlock("cracked_diorite_bricks"))
                .put(getGufyBlock("diorite_bricks_stairs"), getGufyBlock("cracked_diorite_bricks_stairs"))
                .put(getGufyBlock("diorite_bricks_slab"), getGufyBlock("cracked_diorite_bricks_slab"))
                .put(getGufyBlock("diorite_bricks_verticalslab"), getGufyBlock("cracked_diorite_bricks_verticalslab"))
                .put(getGufyBlock("diorite_bricks_wall"), getGufyBlock("cracked_diorite_bricks_wall"))
                .put(getGufyBlock("diorite_bricks_hopper"), getGufyBlock("cracked_diorite_bricks_hopper"))
                .put(getGufyBlock("diorite_bricks_post"), getGufyBlock("cracked_diorite_bricks_post"))
                // DIORITE TILES
                .put(getGufyBlock("diorite_cobble_bricks"), getGufyBlock("cracked_diorite_cobble_bricks"))
                .put(getGufyBlock("diorite_cobble_bricks_stairs"), getGufyBlock("cracked_diorite_cobble_bricks_stairs"))
                .put(getGufyBlock("diorite_cobble_bricks_slab"), getGufyBlock("cracked_diorite_cobble_bricks_slab"))
                .put(getGufyBlock("diorite_cobble_bricks_verticalslab"), getGufyBlock("cracked_diorite_cobble_bricks_verticalslab"))
                .put(getGufyBlock("diorite_cobble_bricks_wall"), getGufyBlock("cracked_diorite_cobble_bricks_wall"))
                .put(getGufyBlock("diorite_cobble_bricks_hopper"), getGufyBlock("cracked_diorite_cobble_bricks_hopper"))
                .put(getGufyBlock("diorite_cobble_bricks_post"), getGufyBlock("cracked_diorite_cobble_bricks_post"))
                // GRANITE BRICKS
                .put(getGufyBlock("granite_bricks"), getGufyBlock("cracked_granite_bricks"))
                .put(getGufyBlock("granite_bricks_stairs"), getGufyBlock("cracked_granite_bricks_stairs"))
                .put(getGufyBlock("granite_bricks_slab"), getGufyBlock("cracked_granite_bricks_slab"))
                .put(getGufyBlock("granite_bricks_verticalslab"), getGufyBlock("cracked_granite_bricks_verticalslab"))
                .put(getGufyBlock("granite_bricks_wall"), getGufyBlock("cracked_granite_bricks_wall"))
                .put(getGufyBlock("granite_bricks_hopper"), getGufyBlock("cracked_granite_bricks_hopper"))
                .put(getGufyBlock("granite_bricks_post"), getGufyBlock("cracked_granite_bricks_post"))
                // GRANITE TILES
                .put(getGufyBlock("granite_cobble_bricks"), getGufyBlock("cracked_granite_cobble_bricks"))
                .put(getGufyBlock("granite_cobble_bricks_stairs"), getGufyBlock("cracked_granite_cobble_bricks_stairs"))
                .put(getGufyBlock("granite_cobble_bricks_slab"), getGufyBlock("cracked_granite_cobble_bricks_slab"))
                .put(getGufyBlock("granite_cobble_bricks_verticalslab"), getGufyBlock("cracked_granite_cobble_bricks_verticalslab"))
                .put(getGufyBlock("granite_cobble_bricks_wall"), getGufyBlock("cracked_granite_cobble_bricks_wall"))
                .put(getGufyBlock("granite_cobble_bricks_hopper"), getGufyBlock("cracked_granite_cobble_bricks_hopper"))
                .put(getGufyBlock("granite_cobble_bricks_post"), getGufyBlock("cracked_granite_cobble_bricks_post"))
                // ANDESITE BRICKS
                .put(getGufyBlock("andesite_bricks"), getGufyBlock("cracked_andesite_bricks"))
                .put(getGufyBlock("andesite_bricks_stairs"), getGufyBlock("cracked_andesite_bricks_stairs"))
                .put(getGufyBlock("andesite_bricks_slab"), getGufyBlock("cracked_andesite_bricks_slab"))
                .put(getGufyBlock("andesite_bricks_verticalslab"), getGufyBlock("cracked_andesite_bricks_verticalslab"))
                .put(getGufyBlock("andesite_bricks_wall"), getGufyBlock("cracked_andesite_bricks_wall"))
                .put(getGufyBlock("andesite_bricks_hopper"), getGufyBlock("cracked_andesite_bricks_hopper"))
                .put(getGufyBlock("andesite_bricks_post"), getGufyBlock("cracked_andesite_bricks_post"))
                // NETHER BRICKS
                .put(Blocks.NETHER_BRICKS, Blocks.CRACKED_NETHER_BRICKS)
                .put(Blocks.NETHER_BRICK_STAIRS, getGufyBlock("cracked_nether_bricks_stairs"))
                .put(Blocks.NETHER_BRICK_SLAB, getGufyBlock("cracked_nether_bricks_slab"))
                .put(Blocks.NETHER_BRICK_WALL, getGufyBlock("cracked_nether_bricks_wall"))
                .put(Blocks.NETHER_BRICK_FENCE, getGufyBlock("cracked_nether_bricks_fence"))
                .put(getGufyBlock("cracked_nether_bricks_verticalslab"), getGufyBlock("cracked_nether_bricks_verticalslab"))
                .put(getGufyBlock("cracked_nether_bricks_hopper"), getGufyBlock("cracked_nether_bricks_hopper"))
                // DEEPSLATE BRICKS
                .put(Blocks.DEEPSLATE_BRICKS, Blocks.CRACKED_DEEPSLATE_BRICKS)
                .put(Blocks.DEEPSLATE_BRICK_STAIRS, getGufyBlock("cracked_deepslate_bricks_stairs"))
                .put(Blocks.DEEPSLATE_BRICK_SLAB, getGufyBlock("cracked_deepslate_bricks_slab"))
                .put(Blocks.DEEPSLATE_BRICK_WALL, getGufyBlock("cracked_deepslate_bricks_wall"))
                .put(getGufyBlock("deepslate_bricks_verticalslab"), getGufyBlock("cracked_deepslate_bricks_verticalslab"))
                .put(getGufyBlock("deepslate_bricks_hopper"), getGufyBlock("cracked_deepslate_bricks_hopper"))
                .put(getGufyBlock("deepslate_bricks_post"), getGufyBlock("cracked_deepslate_bricks_post"))
                // DEEPSLATE TILES
                .put(Blocks.DEEPSLATE_TILES, Blocks.CRACKED_DEEPSLATE_TILES)
                .put(Blocks.DEEPSLATE_TILE_STAIRS, getGufyBlock("cracked_deepslate_tiles_stairs"))
                .put(Blocks.DEEPSLATE_TILE_SLAB, getGufyBlock("cracked_deepslate_tiles_slab"))
                .put(Blocks.DEEPSLATE_TILE_WALL, getGufyBlock("cracked_deepslate_tiles_wall"))
                .put(getGufyBlock("deepslate_tiles_verticalslab"), getGufyBlock("cracked_deepslate_tiles_verticalslab"))
                .put(getGufyBlock("deepslate_tiles_hopper"), getGufyBlock("cracked_deepslate_tiles_hopper"))
                .put(getGufyBlock("deepslate_tiles_post"), getGufyBlock("cracked_deepslate_tiles_post"))
                // POLISHED BLACKSTONE BRICKS
                .put(Blocks.POLISHED_BLACKSTONE_BRICKS, Blocks.CRACKED_POLISHED_BLACKSTONE_BRICKS)
                .put(Blocks.POLISHED_BLACKSTONE_BRICK_STAIRS, getGufyBlock("cracked_polished_blackstone_brick_stairs"))
                .put(Blocks.POLISHED_BLACKSTONE_BRICK_SLAB, getGufyBlock("cracked_polished_blackstone_brick_slab"))
                .put(Blocks.POLISHED_BLACKSTONE_BRICK_WALL, getGufyBlock("cracked_polished_blackstone_brick_wall"))
                .put(getGufyBlock("polished_blackstone_brick_verticalslab"), getGufyBlock("cracked_polished_blackstone_brick_verticalslab"))
                .put(getGufyBlock("polished_blackstone_brick_hopper"), getGufyBlock("cracked_polished_blackstone_brick_hopper"))
                .put(getGufyBlock("polished_blackstone_brick_post"), getGufyBlock("cracked_polished_blackstone_brick_post"))
                // SANDSTONE BRICKS
                .put(getGufyBlock("sandstone_bricks"), getGufyBlock("cracked_sandstone_bricks"))
                .put(getGufyBlock("sandstone_bricks_stairs"), getGufyBlock("cracked_sandstone_bricks_stairs"))
                .put(getGufyBlock("sandstone_bricks_slab"), getGufyBlock("cracked_sandstone_bricks_slab"))
                .put(getGufyBlock("sandstone_bricks_verticalslab"), getGufyBlock("cracked_sandstone_bricks_verticalslab"))
                .put(getGufyBlock("sandstone_bricks_wall"), getGufyBlock("cracked_sandstone_bricks_wall"))
                .put(getGufyBlock("sandstone_bricks_hopper"), getGufyBlock("cracked_sandstone_bricks_hopper"))
                .put(getGufyBlock("sandstone_bricks_post"), getGufyBlock("cracked_sandstone_bricks_post"))
                // SANDSTONE TILES
                .put(getGufyBlock("sandstone_cobble_bricks"), getGufyBlock("cracked_sandstone_cobble_bricks"))
                .put(getGufyBlock("sandstone_cobble_bricks_stairs"), getGufyBlock("cracked_sandstone_cobble_bricks_stairs"))
                .put(getGufyBlock("sandstone_cobble_bricks_slab"), getGufyBlock("cracked_sandstone_cobble_bricks_slab"))
                .put(getGufyBlock("sandstone_cobble_bricks_verticalslab"), getGufyBlock("cracked_sandstone_cobble_bricks_verticalslab"))
                .put(getGufyBlock("sandstone_cobble_bricks_wall"), getGufyBlock("cracked_sandstone_cobble_bricks_wall"))
                .put(getGufyBlock("sandstone_cobble_bricks_hopper"), getGufyBlock("cracked_sandstone_cobble_bricks_hopper"))
                .put(getGufyBlock("sandstone_cobble_bricks_post"), getGufyBlock("cracked_sandstone_cobble_bricks_post"))
                // RED SANDSTONE BRICKS
                .put(getGufyBlock("red_sandstone_bricks"), getGufyBlock("cracked_red_sandstone_bricks"))
                .put(getGufyBlock("red_sandstone_bricks_stairs"), getGufyBlock("cracked_red_sandstone_bricks_stairs"))
                .put(getGufyBlock("red_sandstone_bricks_slab"), getGufyBlock("cracked_red_sandstone_bricks_slab"))
                .put(getGufyBlock("red_sandstone_bricks_verticalslab"), getGufyBlock("cracked_red_sandstone_bricks_verticalslab"))
                .put(getGufyBlock("red_sandstone_bricks_wall"), getGufyBlock("cracked_red_sandstone_bricks_wall"))
                .put(getGufyBlock("red_sandstone_bricks_hopper"), getGufyBlock("cracked_red_sandstone_bricks_hopper"))
                .put(getGufyBlock("red_sandstone_bricks_post"), getGufyBlock("cracked_red_sandstone_bricks_post"))
                // RED SANDSTONE TILES
                .put(getGufyBlock("red_sandstone_cobble_bricks"), getGufyBlock("cracked_red_sandstone_cobble_bricks"))
                .put(getGufyBlock("red_sandstone_cobble_bricks_stairs"), getGufyBlock("cracked_red_sandstone_cobble_bricks_stairs"))
                .put(getGufyBlock("red_sandstone_cobble_bricks_slab"), getGufyBlock("cracked_red_sandstone_cobble_bricks_slab"))
                .put(getGufyBlock("red_sandstone_cobble_bricks_verticalslab"), getGufyBlock("cracked_red_sandstone_cobble_bricks_verticalslab"))
                .put(getGufyBlock("red_sandstone_cobble_bricks_wall"), getGufyBlock("cracked_red_sandstone_cobble_bricks_wall"))
                .put(getGufyBlock("red_sandstone_cobble_bricks_hopper"), getGufyBlock("cracked_red_sandstone_cobble_bricks_hopper"))
                .put(getGufyBlock("red_sandstone_cobble_bricks_post"), getGufyBlock("cracked_red_sandstone_cobble_bricks_post"))
                // BRICKS
                .put(Blocks.BRICKS, getGufyBlock("cracked_bricks"))
                .put(Blocks.BRICK_STAIRS, getGufyBlock("cracked_bricks_stairs"))
                .put(Blocks.BRICK_SLAB, getGufyBlock("cracked_bricks_slab"))
                .put(Blocks.BRICK_WALL, getGufyBlock("cracked_bricks_wall"))
                .put(getGufyBlock("brick_verticalslab"), getGufyBlock("cracked_bricks_verticalslab"))
                .put(getGufyBlock("brick_hopper"), getGufyBlock("cracked_bricks_hopper"))
                .put(getGufyBlock("brick_post"), getGufyBlock("cracked_bricks_post"))
                // FRAMED
                .put(getGufyBlock("oak_framed_terracotta"), getGufyBlock("oak_framed_terracotta_left"))
                .put(getGufyBlock("oak_framed_terracotta_left"), getGufyBlock("oak_framed_terracotta_right"))
                .put(getGufyBlock("oak_framed_terracotta_right"), getGufyBlock("oak_framed_terracotta_cross"))
                .put(getGufyBlock("oak_framed_terracotta_cross"), getGufyBlock("oak_framed_terracotta"))
                .put(getGufyBlock("spruce_framed_terracotta"), getGufyBlock("spruce_framed_terracotta_left"))
                .put(getGufyBlock("spruce_framed_terracotta_left"), getGufyBlock("spruce_framed_terracotta_right"))
                .put(getGufyBlock("spruce_framed_terracotta_right"), getGufyBlock("spruce_framed_terracotta_cross"))
                .put(getGufyBlock("spruce_framed_terracotta_cross"), getGufyBlock("spruce_framed_terracotta"))
                .put(getGufyBlock("birch_framed_terracotta"), getGufyBlock("birch_framed_terracotta_left"))
                .put(getGufyBlock("birch_framed_terracotta_left"), getGufyBlock("birch_framed_terracotta_right"))
                .put(getGufyBlock("birch_framed_terracotta_right"), getGufyBlock("birch_framed_terracotta_cross"))
                .put(getGufyBlock("birch_framed_terracotta_cross"), getGufyBlock("birch_framed_terracotta"))
                .put(getGufyBlock("dark_oak_framed_terracotta"), getGufyBlock("dark_oak_framed_terracotta_left"))
                .put(getGufyBlock("dark_oak_framed_terracotta_left"), getGufyBlock("dark_oak_framed_terracotta_right"))
                .put(getGufyBlock("dark_oak_framed_terracotta_right"), getGufyBlock("dark_oak_framed_terracotta_cross"))
                .put(getGufyBlock("dark_oak_framed_terracotta_cross"), getGufyBlock("dark_oak_framed_terracotta"))
                .put(getGufyBlock("jungle_framed_terracotta"), getGufyBlock("jungle_framed_terracotta_left"))
                .put(getGufyBlock("jungle_framed_terracotta_left"), getGufyBlock("jungle_framed_terracotta_right"))
                .put(getGufyBlock("jungle_framed_terracotta_right"), getGufyBlock("jungle_framed_terracotta_cross"))
                .put(getGufyBlock("jungle_framed_terracotta_cross"), getGufyBlock("jungle_framed_terracotta"))
                .put(getGufyBlock("acacia_framed_terracotta"), getGufyBlock("acacia_framed_terracotta_left"))
                .put(getGufyBlock("acacia_framed_terracotta_left"), getGufyBlock("acacia_framed_terracotta_right"))
                .put(getGufyBlock("acacia_framed_terracotta_right"), getGufyBlock("acacia_framed_terracotta_cross"))
                .put(getGufyBlock("acacia_framed_terracotta_cross"), getGufyBlock("acacia_framed_terracotta"))
                .put(getGufyBlock("crimson_framed_terracotta"), getGufyBlock("crimson_framed_terracotta_left"))
                .put(getGufyBlock("crimson_framed_terracotta_left"), getGufyBlock("crimson_framed_terracotta_right"))
                .put(getGufyBlock("crimson_framed_terracotta_right"), getGufyBlock("crimson_framed_terracotta_cross"))
                .put(getGufyBlock("crimson_framed_terracotta_cross"), getGufyBlock("crimson_framed_terracotta"))
                .put(getGufyBlock("warped_framed_terracotta"), getGufyBlock("warped_framed_terracotta_left"))
                .put(getGufyBlock("warped_framed_terracotta_left"), getGufyBlock("warped_framed_terracotta_right"))
                .put(getGufyBlock("warped_framed_terracotta_right"), getGufyBlock("warped_framed_terracotta_cross"))
                .put(getGufyBlock("warped_framed_terracotta_cross"), getGufyBlock("warped_framed_terracotta"))
                .put(getGufyBlock("mangrove_framed_terracotta"), getGufyBlock("mangrove_framed_terracotta_left"))
                .put(getGufyBlock("mangrove_framed_terracotta_left"), getGufyBlock("mangrove_framed_terracotta_right"))
                .put(getGufyBlock("mangrove_framed_terracotta_right"), getGufyBlock("mangrove_framed_terracotta_cross"))
                .put(getGufyBlock("mangrove_framed_terracotta_cross"), getGufyBlock("mangrove_framed_terracotta"))
                .put(getGufyBlock("cherry_framed_terracotta"), getGufyBlock("cherry_framed_terracotta_left"))
                .put(getGufyBlock("cherry_framed_terracotta_left"), getGufyBlock("cherry_framed_terracotta_right"))
                .put(getGufyBlock("cherry_framed_terracotta_right"), getGufyBlock("cherry_framed_terracotta_cross"))
                .put(getGufyBlock("cherry_framed_terracotta_cross"), getGufyBlock("cherry_framed_terracotta"))
                .put(getGufyBlock("bamboo_framed_terracotta"), getGufyBlock("bamboo_framed_terracotta_left"))
                .put(getGufyBlock("bamboo_framed_terracotta_left"), getGufyBlock("bamboo_framed_terracotta_right"))
                .put(getGufyBlock("bamboo_framed_terracotta_right"), getGufyBlock("bamboo_framed_terracotta_cross"))
                .put(getGufyBlock("bamboo_framed_terracotta_cross"), getGufyBlock("bamboo_framed_terracotta"))
                .put(getGufyBlock("mushroom_framed_terracotta"), getGufyBlock("mushroom_framed_terracotta_left"))
                .put(getGufyBlock("mushroom_framed_terracotta_left"), getGufyBlock("mushroom_framed_terracotta_right"))
                .put(getGufyBlock("mushroom_framed_terracotta_right"), getGufyBlock("mushroom_framed_terracotta_cross"))
                .put(getGufyBlock("mushroom_framed_terracotta_cross"), getGufyBlock("mushroom_framed_terracotta"))
                .put(getGufyBlock("pale_oak_framed_terracotta"), getGufyBlock("pale_oak_framed_terracotta_left"))
                .put(getGufyBlock("pale_oak_framed_terracotta_left"), getGufyBlock("pale_oak_framed_terracotta_right"))
                .put(getGufyBlock("pale_oak_framed_terracotta_right"), getGufyBlock("pale_oak_framed_terracotta_cross"))
                .put(getGufyBlock("pale_oak_framed_terracotta_cross"), getGufyBlock("pale_oak_framed_terracotta"))
                // CARVED LOGS
                .put(Blocks.STRIPPED_ACACIA_WOOD, getGufyBlock("chiseled_stripped_acacia_wood"))
                .put(Blocks.STRIPPED_BIRCH_WOOD, getGufyBlock("chiseled_stripped_birch_wood"))
                .put(Blocks.STRIPPED_BAMBOO_BLOCK, getGufyBlock("chiseled_stripped_bamboo_block"))
                .put(Blocks.STRIPPED_CRIMSON_HYPHAE, getGufyBlock("chiseled_stripped_crimson_hyphae"))
                .put(Blocks.STRIPPED_DARK_OAK_WOOD, getGufyBlock("chiseled_stripped_dark_oak_wood"))
                .put(Blocks.STRIPPED_JUNGLE_WOOD, getGufyBlock("chiseled_stripped_jungle_wood"))
                .put(Blocks.STRIPPED_OAK_WOOD, getGufyBlock("chiseled_stripped_oak_wood"))
                .put(Blocks.STRIPPED_MANGROVE_WOOD, getGufyBlock("chiseled_stripped_mangrove_wood"))
                .put(Blocks.STRIPPED_CHERRY_WOOD, getGufyBlock("chiseled_stripped_cherry_wood"))
                .put(Blocks.STRIPPED_SPRUCE_WOOD, getGufyBlock("chiseled_stripped_spruce_wood"))
                .put(Blocks.STRIPPED_WARPED_HYPHAE, getGufyBlock("chiseled_stripped_warped_hyphae"))
                .put(Blocks.STRIPPED_PALE_OAK_WOOD, getGufyBlock("chiseled_stripped_pale_oak_wood"))

                .build();
    });
}
